# Generated by Django 4.2.1 on 2023-05-30 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='gifts',
            new_name='gifs',
        ),
        migrations.RenameField(
            model_name='gif',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
