# Generated by Django 4.2.1 on 2023-05-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_animals_family'),
    ]

    operations = [
        migrations.AddField(
            model_name='animals',
            name='name',
            field=models.CharField(default='cat', max_length=20),
        ),
    ]
